name: Java CI with Maven

# 获取代码
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 开始工作
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 设置JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'

      # 3. 编译打包
      - name: Build with Maven
        run: mvn clean package -DskipTests -P prod

